### ISSUE TITLE
Error during make - isarray is a built-in function

### ISSUE THREAD

**Issue by DanRStevens** [devkev/xlibtrace#1]
> /bin/bash ./libxlibtrace-functions.h.sh
> awk: cmd. line:29: function isarray(t) {
> awk: cmd. line:29:          ^ `isarray' is a built-in function, it cannot be redefined

Edit: Tested on Ubuntu 20.04
Renaming the function allows build to proceed, though it fails later on.

**Comment by devkev** [comment]
Thanks.  I haven't used this in years.  Feel free to send a PR to rename the function, and another issue for the later failure.
