### ISSUE TITLE
Awk Warnings for `how` parameter

### ISSUE THREAD

**Issue by DanRStevens** [devkev/xlibtrace#4]
When running `make` a large number of warnings are generated by the `./libxlibtrace-functions.h.sh` script.
Warnings are of the form:
> awk: cmd. line:84: (FILENAME=- FNR=2911) warning: gensub: third argument `' treated as 1

Documentation:
[Gawk String Manipulation Functions](https://www.gnu.org/software/gawk/manual/html_node/String-Functions.html)

According to the documentation for the `gensub` function, the third argument is `how`. When set to `"g"` it will do a global replace, otherwise it marks which match should be replaced. When the argument is negative (or absent as in the code), it appears to default to a value of `"1"` (replace the first occurrence).

These warnings can be silenced by passing `"1"` instead of an empty string `""`.

This change would produce a merge conflict with #2.

----

Edit: These warnings are seen on Ubuntu 20.04. When experimenting with older versions of Ubuntu, the project was able to compile without warnings or errors (with #2 and #3 applied).

**Comment by devkev** [comment]
Thanks for filing this, and for your PRs.  I'm having a proper look to see what else might be necessary to get it to compile again, but hope to soon merge them (and a fix for this also).  Thanks again!

**Comment by devkev** [comment]
Hi, I've pushed a bunch of commits for this and most of the other issues/PRs you've reported.  These are enough for me to compile successfully on Ubuntu 18.04.  Can you confirm that they work for you also?  Happy to also look into any Ubuntu 20.04 issues now at this point (if any remain).

**Comment by DanRStevens** [comment]
Thank you very much for the updates. I'll test the changes with Ubuntu 18.04 and Ubuntu 20.04 and provide the results.
